### ISSUE TITLE
File editing messes up indenting

### ISSUE THREAD

**Issue by ddgenome** [atomist/yaml-updater#2]
Some how a top-level property got improperly indented:

https://github.com/ivans-innovation-lab/my-company-monolith/pull/6/commits/3d02c39783283dcc29da877c8fb005d0c7383e1f#diff-256c57f5b357be82840a9b2207f0dcd5R25

**Comment by ddgenome** [comment]
Original YAML:

```yaml
info:
  app:
    name: Monolitihic
    description: Monolitihic - Application - All in one ;)

server:
  port: 8080
  
management:
  cloudfoundry:
    skip-ssl-validation: true
  info:
    git:
      mode: full

  
  
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.idugalic: DEBUG
    
authserver:
  hostname: localhost
  port: 9999
  contextPath: uaa


      
security:
  oauth2:
    resource:
      jwt:
        keyUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      
flyway:
  locations: db/migration/h2

---
spring:
  profiles: cloud
  jpa:
    database:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${vcap.services.mysql.credentials.jdbcUrl}
    username: ${vcap.services.mysql.credentials.username}
    password: ${vcap.services.mysql.credentials.password}
    
flyway:
  locations: db/migration/mysql
```
