### ISSUE TITLE
Respect indentation of comments

### ISSUE THREAD

**Issue by mxstbr** [atomist/yaml-updater#25]
Original YAML:

```yaml
defaultCacheConfig:
  maxAge: 900
# Environments
environments:
  staging:
    app: cf-staging
```

Update data:

```json
{
  "defaultCacheConfig": {
    "swr": 900
  }
}
```

Result:

```yaml
defaultCacheConfig:
  maxAge: 900
# Environments
  swr: 900
environments:
  staging:
    app: cf-staging
```

<details>
  <summary>Click to see a reproduction script</summary>

```JS
const { updateYamlDocument } = require('@atomist/yaml-updater')

const yaml = `defaultCacheConfig:
  maxAge: 900
# Environments
environments:
  staging:
    app: cf-staging`

const update = {
  defaultCacheConfig: {
    swr: 900,
  },
}

console.log(updateYamlDocument(update, yaml))
```

run it with

```
node <filename>.js
```

</details>
